service: budgetcontrol-ms-entries
provider:
  name: aws
  region: eu-west-1
  timeout: 60
  runtime: provided.al2
  environment:
    APP_NAME: ${env:APP_NAME}
    APP_ENV: ${env:APP_ENV}
    APP_VERSION: ${env:APP_VERSION}
    APP_KEY: ${env:APP_KEY}
    DB_CONNECTION: ${env:DB_CONNECTION}
    DB_HOST: ${env:DB_HOST}
    DB_DATABASE: ${env:DB_DATABASE}
    DB_PORT: ${env:DB_PORT}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    LOGTAIL_API_KEY: ${env:LOGTAIL_API_KEY, ''}
    LOG_CHANNEL: ${env:LOG_CHANNEL}
  deploymentBucket:
    name: serverless-framework-deployments-eu-west-1-41d5edce-535f
plugins:
  - ./vendor/bref/bref
functions:
  web:
    handler: public/index.php
    timeout: 60
    layers:
      - arn:aws:lambda:eu-west-1:534081306603:layer:php-82-fpm:99
    events:
      - httpApi: '*'
package:
  exclude:
    - '.git/**'
    - '.idea/**'
    - 'node_modules/**'
    - 'tests/**'
    - 'storage/logs/**'
    - '.env.*'
  include:
    - 'public/**'
    - 'vendor/**'
    - 'bootstrap/**'
    - 'storage/**'